apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-probe
  labels:
    version: "1.0"
  annotations:
    description: This is my first pod with probe to check readiness, liveness and healthy
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3